CREATE TABLE `dbchallenge`.`dbchallenge` (
  `seq` BIGINT NULL,
  `yn` TINYINT NULL,
  `age` TINYINT NULL,
  `birthday` DATE NULL,
  `bool` TINYINT NULL,
  `ccnumber` INT NULL,
  `city` VARCHAR(45) NULL,
  `date` DATE NULL,
  `digit` INT NULL,
  `dollar` VARCHAR(45) NULL,
  `first` VARCHAR(45) NULL,
  `chifre` INT NULL,
  `name` VARCHAR(45) NULL,
  `last` VARCHAR(45) NULL,
  `paragraph` VARCHAR(45) NULL,
  `sentence` VARCHAR(45) NULL);